#!/usr/bin/env python3
"""Generate a polished metrics summary report for the Autobahn Perception Stack.

Runs CLEARMOTEvaluator on synthetic tracking data (perfect and imperfect
scenarios), loads baseline benchmarks, and produces a clean markdown report
saved to ``demo/METRICS.md``.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Path setup so we can import project modules regardless of working directory
# ---------------------------------------------------------------------------
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.evaluation.mot_metrics import CLEARMOTEvaluator  # noqa: E402

# ---------------------------------------------------------------------------
# Rich console (best-effort import)
# ---------------------------------------------------------------------------
try:
    from rich.console import Console
    from rich.table import Table
except ImportError:
    Console = None  # type: ignore[assignment,misc]
    Table = None  # type: ignore[assignment,misc]

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent.parent
BASELINE_PATH = PROJECT_ROOT / "baselines" / "benchmark_baseline.json"
OUTPUT_PATH = PROJECT_ROOT / "demo" / "METRICS.md"


# ---------------------------------------------------------------------------
# Synthetic ground-truth / prediction data
# ---------------------------------------------------------------------------

def _perfect_scenario():
    """3 frames, 2 objects each. Predictions match GT exactly."""
    gt_frames = [
        [(1, (100, 100, 200, 200)), (2, (300, 300, 400, 400))],
        [(1, (110, 100, 210, 200)), (2, (310, 300, 410, 400))],
        [(1, (120, 100, 220, 200)), (2, (320, 300, 420, 400))],
    ]
    pred_frames = [
        [(1, (100, 100, 200, 200)), (2, (300, 300, 400, 400))],
        [(1, (110, 100, 210, 200)), (2, (310, 300, 410, 400))],
        [(1, (120, 100, 220, 200)), (2, (320, 300, 420, 400))],
    ]
    return gt_frames, pred_frames


def _imperfect_scenario():
    """3 frames, 2 objects. Frame 2 has an ID switch (pred IDs swap)."""
    gt_frames = [
        [(1, (100, 100, 200, 200)), (2, (300, 300, 400, 400))],
        [(1, (110, 100, 210, 200)), (2, (310, 300, 410, 400))],
        [(1, (120, 100, 220, 200)), (2, (320, 300, 420, 400))],
    ]
    pred_frames = [
        [(1, (100, 100, 200, 200)), (2, (300, 300, 400, 400))],
        # ID switch: pred IDs are swapped relative to GT
        [(2, (110, 100, 210, 200)), (1, (310, 300, 410, 400))],
        [(2, (120, 100, 220, 200)), (1, (320, 300, 420, 400))],
    ]
    return gt_frames, pred_frames


# ---------------------------------------------------------------------------
# Metric evaluation
# ---------------------------------------------------------------------------

def _evaluate_scenario(label: str, gt_frames, pred_frames) -> dict:
    evaluator = CLEARMOTEvaluator(iou_threshold=0.5)
    results = evaluator.evaluate_full(gt_frames, pred_frames)
    return {"label": label, **results}


# ---------------------------------------------------------------------------
# Markdown generation
# ---------------------------------------------------------------------------

def _fmt(value, decimals: int = 4) -> str:
    if isinstance(value, float):
        return f"{value:.{decimals}f}"
    return str(value)


def _generate_markdown(
    baseline: dict,
    perfect: dict,
    imperfect: dict,
) -> str:
    lines: list[str] = []
    lines.append("# Autobahn Perception Stack -- Metrics Report")
    lines.append("")
    lines.append("> Auto-generated by `scripts/generate_metrics_report.py`")
    lines.append("")

    # --- Detection Performance ---
    lines.append("## Detection Performance")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| mAP (baseline) | {baseline.get('mAP', 'N/A')} |")
    lines.append(f"| Inference Latency | {baseline.get('latency_ms', 'N/A')} ms |")
    lines.append("| Model | YOLOv8n |")
    lines.append("| Runtime Backends | PyTorch, ONNX, TensorRT |")
    lines.append("")

    # --- Tracking Performance ---
    lines.append("## Tracking Performance")
    lines.append("")
    lines.append("Evaluated using CLEAR MOT metrics on synthetic sequences.")
    lines.append("")
    lines.append("| Metric | Perfect Tracking | Imperfect (ID Switch) |")
    lines.append("|--------|:----------------:|:---------------------:|")
    lines.append(f"| MOTA | {_fmt(perfect['MOTA'])} | {_fmt(imperfect['MOTA'])} |")
    lines.append(f"| MOTP | {_fmt(perfect['MOTP'])} | {_fmt(imperfect['MOTP'])} |")
    lines.append(f"| IDF1 | {_fmt(perfect['IDF1'])} | {_fmt(imperfect['IDF1'])} |")
    lines.append(f"| HOTA | {_fmt(perfect['HOTA'])} | {_fmt(imperfect['HOTA'])} |")
    lines.append(f"| ID Switches | {perfect['IDSW']} | {imperfect['IDSW']} |")
    lines.append(f"| False Positives | {perfect['FP']} | {imperfect['FP']} |")
    lines.append(f"| False Negatives | {perfect['FN']} | {imperfect['FN']} |")
    lines.append(f"| Total GT Objects | {perfect['total_gt']} | {imperfect['total_gt']} |")
    lines.append("")

    # --- System Performance ---
    lines.append("## System Performance")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Target FPS | {baseline.get('fps', 'N/A')} |")
    lines.append(f"| Latency Budget | {baseline.get('latency_ms', 'N/A')} ms |")
    lines.append("| Parallel Execution | Thread-pool stage parallelism |")
    lines.append("| Adaptive Skip | Dynamic frame-skip under degradation |")
    lines.append("| Health Monitor | Watchdog with configurable miss threshold |")
    lines.append("")

    # --- Safety Features ---
    lines.append("## Safety Features")
    lines.append("")
    lines.append("| Module | Description |")
    lines.append("|--------|-------------|")
    lines.append("| FCW (Forward Collision Warning) | TTC-based collision warning with ego-lane filtering and EMA smoothing |")
    lines.append("| LDW (Lane Departure Warning) | Persistent lane offset monitoring with jitter-gated activation |")
    lines.append("| BSD (Blind Spot Detection) | Lateral blind-spot and rear cross-traffic alerts |")
    lines.append("| Sensor Health Monitor | Camera brightness/blur, LIDAR point density, radar consistency scoring |")
    lines.append("| Plausibility Checker | ISO 26262 compliant velocity, position jump, and overlap validation |")
    lines.append("| ASIL Classifier | Automotive Safety Integrity Level classification |")
    lines.append("| DTC Logger | Diagnostic Trouble Code logging for safety violations |")
    lines.append("| Redundant Detector | Dual-model agreement check for safety-critical detections |")
    lines.append("")

    # --- Sensor Fusion ---
    lines.append("## Sensor Fusion")
    lines.append("")
    lines.append("| Capability | Details |")
    lines.append("|------------|---------|")
    lines.append("| Radar Processing | RCS-filtered, DBSCAN-clustered radar detections |")
    lines.append("| Radar-Camera Fusion | Projection-based matching of radar returns to camera bounding boxes |")
    lines.append("| LIDAR Processing | Voxel downsampling, RANSAC ground removal, DBSCAN clustering |")
    lines.append("| LIDAR-Camera Fusion | IoU-weighted late fusion of 3D LIDAR and 2D camera detections |")
    lines.append("| BEV Encoding | Bird's-eye-view grid encoding from LIDAR point clouds |")
    lines.append("| Kalman Fusion | Per-track Kalman filter state estimation with temporal prediction |")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Report generated by the Autobahn Perception Stack evaluation pipeline.*")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Rich stdout summary
# ---------------------------------------------------------------------------

def _print_rich_summary(baseline: dict, perfect: dict, imperfect: dict) -> None:
    if Console is None or Table is None:
        print("[INFO] Rich not installed -- skipping console table.")
        return

    console = Console()
    console.print()
    console.rule("[bold blue]Autobahn Perception Stack -- Metrics Summary[/bold blue]")
    console.print()

    # --- Detection table ---
    det_table = Table(title="Detection Performance", show_lines=True)
    det_table.add_column("Metric", style="cyan", no_wrap=True)
    det_table.add_column("Value", justify="right", style="green")
    det_table.add_row("mAP (baseline)", str(baseline.get("mAP", "N/A")))
    det_table.add_row("Latency", f"{baseline.get('latency_ms', 'N/A')} ms")
    det_table.add_row("FPS (baseline)", str(baseline.get("fps", "N/A")))
    console.print(det_table)
    console.print()

    # --- Tracking table ---
    trk_table = Table(title="Tracking Performance (CLEAR MOT)", show_lines=True)
    trk_table.add_column("Metric", style="cyan", no_wrap=True)
    trk_table.add_column("Perfect", justify="right", style="green")
    trk_table.add_column("Imperfect", justify="right", style="yellow")

    for key in ("MOTA", "MOTP", "IDF1", "HOTA"):
        trk_table.add_row(key, _fmt(perfect[key]), _fmt(imperfect[key]))
    trk_table.add_row("ID Switches", str(perfect["IDSW"]), str(imperfect["IDSW"]))
    trk_table.add_row("FP", str(perfect["FP"]), str(imperfect["FP"]))
    trk_table.add_row("FN", str(perfect["FN"]), str(imperfect["FN"]))
    console.print(trk_table)
    console.print()

    # --- Safety table ---
    safety_table = Table(title="Safety Modules", show_lines=True)
    safety_table.add_column("Module", style="cyan")
    safety_table.add_column("Status", justify="center", style="green")
    for module in ("FCW", "LDW", "BSD", "Sensor Health", "Plausibility", "ASIL", "DTC Logger", "Redundant Detector"):
        safety_table.add_row(module, "Implemented")
    console.print(safety_table)
    console.print()

    # --- Fusion table ---
    fusion_table = Table(title="Sensor Fusion Capabilities", show_lines=True)
    fusion_table.add_column("Sensor", style="cyan")
    fusion_table.add_column("Pipeline", style="green")
    fusion_table.add_row("Radar", "Process + Camera Fusion")
    fusion_table.add_row("LIDAR", "Voxel + Ground Removal + Cluster + Camera Fusion")
    fusion_table.add_row("Camera", "YOLO Detection + DeepSORT Tracking")
    fusion_table.add_row("Kalman", "Per-track state estimation + temporal prediction")
    console.print(fusion_table)
    console.print()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    # 1. Evaluate perfect scenario
    gt_perfect, pred_perfect = _perfect_scenario()
    perfect = _evaluate_scenario("Perfect Tracking", gt_perfect, pred_perfect)

    # 2. Evaluate imperfect scenario
    gt_imperfect, pred_imperfect = _imperfect_scenario()
    imperfect = _evaluate_scenario("Imperfect (ID Switch)", gt_imperfect, pred_imperfect)

    # 3. Load baseline
    with open(BASELINE_PATH) as f:
        baseline = json.load(f)

    # 4. Generate markdown report
    md = _generate_markdown(baseline, perfect, imperfect)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(md)
    print(f"[OK] Metrics report saved to {OUTPUT_PATH}")

    # 5. Print Rich summary to stdout
    _print_rich_summary(baseline, perfect, imperfect)


if __name__ == "__main__":
    main()
